### ISSUE TITLE
Bug with dead batteries

### ISSUE THREAD

**Issue by Stratdan** [eXish/lc-batteries#5]
When i have a flashlight that has no battery left then use a battery,
i cannot turn my flashlight on until i drop it and pick it up again

https://github.com/eXish/lc-batteries/assets/85818065/25e29cb4-36dd-4117-a1a3-df04ecc6062c

**Comment by eXish** [comment]
Can you send a list of the mods you got other than Batteries? Or is it just Batteries that you have? I havent gotten to checking if this happens with just Batteries alone but I don't think I've ever ran into this when I've played with the mod before.

**Comment by eXish** [comment]
Turns out it does just happen with Batteries alone, sorry about that. Issue has been fixed in version 1.1.0
